services:
  - type: web
    name: telegram-fam-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELEGRAM_SESSION_STRING
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
